# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/freq_div_sig.xdc

# Block Designs: bd/vga/vga.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga || ORIG_REF_NAME==vga} -quiet] -quiet

# IP: bd/vga/ip/vga_clk_wiz_0_0/vga_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_clk_wiz_0_0 || ORIG_REF_NAME==vga_clk_wiz_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_reset_inv_0_0/vga_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_reset_inv_0_0 || ORIG_REF_NAME==vga_reset_inv_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_vga_controller_0_0/vga_vga_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_vga_controller_0_0 || ORIG_REF_NAME==vga_vga_controller_0_0} -quiet] -quiet

# IP: bd/vga/ip/vga_pixel_gen_0_0/vga_pixel_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vga_pixel_gen_0_0 || ORIG_REF_NAME==vga_pixel_gen_0_0} -quiet] -quiet

# XDC: c:/Users/50/Desktop/vLabs/freq_div/freq_div.gen/sources_1/bd/vga/vga_ooc.xdc
