# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/50/Desktop/vLabs/clock_test/clock_test.srcs/sources_1/ip/clk_wiz_22/clk_wiz_22.xci
# IP: The module: 'clk_wiz_22' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/50/Desktop/vLabs/clock_test/clock_test.gen/sources_1/ip/clk_wiz_22/clk_wiz_22_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_22'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/50/Desktop/vLabs/clock_test/clock_test.gen/sources_1/ip/clk_wiz_22/clk_wiz_22.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/50/Desktop/vLabs/clock_test/clock_test.gen/sources_1/ip/clk_wiz_22/clk_wiz_22_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/50/Desktop/vLabs/clock_test/clock_test.srcs/sources_1/ip/clk_wiz_22/clk_wiz_22.xci
# IP: The module: 'clk_wiz_22' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/50/Desktop/vLabs/clock_test/clock_test.gen/sources_1/ip/clk_wiz_22/clk_wiz_22_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/50/Desktop/vLabs/clock_test/clock_test.gen/sources_1/ip/clk_wiz_22/clk_wiz_22.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/50/Desktop/vLabs/clock_test/clock_test.gen/sources_1/ip/clk_wiz_22/clk_wiz_22_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
